### ISSUE TITLE
Enable requests caching only for a subset of URLs

### ISSUE THREAD

**Issue by yakutovicha** [aiidalab/aiidalab#196]
Now requests caching is enabled globally, this is quite bad because any import of aiidalab package might result in a strange behaviour of other tools that rely on `requests` package.

Unfortunately, I do not see a way to enable the caching only for specific URLs. 

**UPD**:
Using [`requests_cache.CachedSession`](https://requests-cache.readthedocs.io/en/stable/user_guide.html#sessions) is the way to go.

**Comment by JWCook** [comment]
Hi there, I came across this while searching for potential requests-cache bugs.

There are a couple things you can do:
* Use [`requests_cache.CachedSession`](https://requests-cache.readthedocs.io/en/stable/user_guide.html#sessions) instead of `requests_cache.install_cache`, and then use a normal `requests.Session` or `requests.get` for requests that you don't want to cache
    * In general that's the preferred way to use it, exactly for the reason you mentioned: so it doesn't unexpectedly affect requests in other projects that import your library
* Use [URL patterns](https://requests-cache.readthedocs.io/en/stable/user_guide.html#url-patterns) to define what requests you do and don't want to cache

You're welcome to [make an issue](https://github.com/reclosedev/requests-cache/issues/new/choose) on the requests-cache repo if you have more questions, or if you have any problems with that.
